"""empty message

Revision ID: c8c7121eb467
Revises: 95f3515817bf
Create Date: 2019-02-21 14:02:39.356794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8c7121eb467'
down_revision = '95f3515817bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
